spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/got_web
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: ${JWT_SECRET:default_secret_key_which_should_be_replaced_in_production}
      expiration: 86400000 # 24 heures en millisecondes
  mail:
    host: localhost
    port: 25
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
            required: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

app:
  name: GOT ERP
  url: http://localhost:8080
  email:
    from: noreply@got-erp.com

logging:
  level:
    org.springframework.security: DEBUG
    org.got.web: DEBUG
