spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/got_web
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      keystore:
        location: classpath:jwt-keystore.p12
        password: ${JWT_KEYSTORE_PASSWORD:changeit}
        alias: ${JWT_KEY_ALIAS:got-jwt-key}
      expiration: ${JWT_EXPIRATION:86400000} # 24 heures
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 jours
      issuer: ${JWT_ISSUER:got-web}
  mail:
    host: localhost
    port: 25
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    webjars-path-pattern: /webjars/**
    web:
      resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/


# Configuration du cache
cache:
  # Configuration Caffeine
  caffeine:
    initial-capacity: ${CACHE_CAFFEINE_INITIAL_CAPACITY:100}
    maximum-size: ${CACHE_CAFFEINE_MAX_SIZE:10000}
    expire-after-write: ${CACHE_CAFFEINE_EXPIRE:21600000} # 6 heures
    expire-after-access: ${CACHE_CAFFEINE_EXPIRE_ACCESS:43200000} # 12 heures
    record-stats: true

springdoc:
  version: 3.0.0
  api-docs:
    path: /swagger/api-docs
    version: openapi_3_0
  swagger-ui:
    enabled: false
    path: /swagger/custom-ui
    config-url: /swagger/swagger-config.json



app:
  name: GOT ERP
  url: http://localhost:8080
  email:
    from: noreply@got-erp.com

logging:
  level:
    org.springframework.security: DEBUG
    org.got.web: DEBUG
    org.springframework.cache: DEBUG
